language: ruby
rvm:
- 2.4.1
env:
  global:
  - secure: RlaP/no+h+knA8bk2ueFj2cF8aR3RAIu49hxo1eMl0Y1XUwNlKVRGbgtSIOzyL86+uzcBMeoiHT9plM25Dx+vNI3Z7xRqPUMO497IDLqFJA5vGG5RsaLc2Grxm35ThMxj5VuYWm1Y916N/nDNXfMyOYkaS3qian1xvK9uI/9whbtRszXVy0XW+6OQqn9qnHf+UB5w0nr2UnoLG10qlELLxGo/nVhxaipjRu4Zs5TZh2O1ovBMboOpoVjIBBCTts28sbpL/MH44M8uKOjLLhGWeF5aOLcnCS+R4rdzvwABjegTXN66qhC46X3+11i9mMgfb8s1KrXLuzcCfVW6dAuPBqZrvr0n9XSD3s+gnhgnl6Y7fNlh88cYWWM3bjl0L4wXxlFZZmb+mivqlUeBACRaHJaSYy8zuZB58JDUv4I6YBojuIfMr8eR5FSlkdcM54PkCgQSfXsaLhx6QMFDnQTnv/g8VB97cO50AA+PnrDK6PgwRrUbCf7VcSXorv1X58kvYldrUKJU9JpffO/oC91RDyYY2FAm1W/y0YDHb8w0zqFqBcD8ZcCR9S/cG5kEw9Bg3mIqRJQfY7o1PGUVeaRZkALfFHpLGWSq8CpaisHRHEVFScwoUezq+k8ry3d6rfr4g8LO/fDT7gQ+LfjIYYGeq3k5RFfE6pDt+nI6LXnY2Y=
#install: make setup
script:
- gem install bundler
- build install
- build exec jekyll build
#after_success:
#- bash .utility/push-site-to-master.sh
